


' Get random integer number from 1 to 8
Function RND1TO8(R)
  LOCAL RR = Int(Rnd(R)*7.98+1.01)
  RND1TO8=RR 
End Function

SUB PUTOBJECT(QX, QY, OBJECT)
LOCAL X, Y, FOUND
FOUND=0
DO WHILE FOUND=0
  X = RND1TO8(1)+((QX-1)*8)
  Y = RND1TO8(1)+((QY-1)*8)
  IF GALAXY(X,Y) = 0 THEN
    FOUND=1
    GALAXY(X,Y) = OBJECT
    PUTX = X : PUTY = Y
  ENDIF 
LOOP
END SUB

FUNCTION COUNTINQUADRANT(QX, QY, OBJECT)
  LOCAL X, Y, RESULT
  RESULT = 0
  FOR Y = 1 TO 8
    FOR X = 1 TO 8
      IF GALAXY(X+(QX-1)*8,Y+(QY-1)*8) = OBJECT THEN RESULT = RESULT + 1
  COUNTINQUADRANT = RESULT
END FUNCTION

SUB PUTOBJECTS(QX, QY, COUNT, OBJECT)
  LOCAL COUNTER
  COUNTER = COUNT
  DO WHILE COUNTER > 0
    COUNTER = COUNTER - 1
    PUTOBJECT QX, QY, OBJECT
  LOOP
END SUB

FUNCTION DRAWOBJECT$(OBJECT)
  LOCAL RESULT$
  RESULT$=FORMAT$(OBJECT)
  IF OBJECT = 0 THEN RESULT$=" " ' KLINGON
  IF OBJECT = 1 THEN RESULT$="K" ' KLINGON
  IF OBJECT = 2 THEN RESULT$="!" ' STARBASE
  IF OBJECT = 3 THEN RESULT$="*" ' STAR 

  IF OBJECT = 9 THEN RESULT$="@" ' ENETRPRIZE 

  DRAWOBJECT$ = RESULT$
END FUNCTION


' ###########################

' GLOBAL TECHNICAL VARIABLES
DIM PUTX, PUTY 

' SET DEFAULTS
DIM GALAXY(64,64)
DIM QUADRNTS(8,8)
DIM ENTERPRISE(10) ' X,Y, [<8 SYSTEMS DAMAGE>]

KLINGONS_TOTAL = 0
STARBASES_TOTAL = 0
STARS_TOTAL = 0



' GENERATING GALAXY
RANDOMIZE EPOCH(NOW) 

FOR QY = 1 TO 8
  FOR QX = 1 TO 8
    KLINGONS_IN_QUADRANT = 0
    R1=Rnd(1)
    If R1>.80 Then KLINGONS_IN_QUADRANT=1
    If R1>.95 Then KLINGONS_IN_QUADRANT=2
    If R1>.98 Then KLINGONS_IN_QUADRANT=3

    STARBASES_IN_QUADRANT = 0
    If Rnd(1)>.96 Then STARBASES_IN_QUADRANT=1

    STARS_IN_QUADRANT = RND1TO8()

    PUTOBJECTS QX, QY, KLINGONS_IN_QUADRANT, 1
    PUTOBJECTS QX, QY, STARBASES_IN_QUADRANT, 2
    PUTOBJECTS QX, QY, STARS_IN_QUADRANT, 3

    KLINGONS_TOTAL = KLINGONS_TOTAL + KLINGONS_IN_QUADRANT
    STARBASES_TOTAL = STARBASES_TOTAL + STARBASES_IN_QUADRANT
    STARS_TOTAL = STARS_TOTAL + STARS_IN_QUADRANT
    
  NEXT QX
NEXT QY

SUB PRINTSYSINFO(SYSID)
  SELECT CASE SYSID   
    CASE 1
      PRINT "        STARDATE          ";Int(T*10)*.1
    CASE 2
      PRINT "        CONDITION          ";CC$
    CASE 3
      PRINT "        QUADRANT          ";Q1;",";Q2
    CASE 4
      PRINT "        SECTOR            ";S1;",";S2
    CASE 5
      PRINT "        PHOTON TORPEDOES  ";Int(P)
    CASE 6
      PRINT "        TOTAL ENERGY      ";Int(E+S)
    CASE 7
      PRINT "        SHIELDS           ";Int(S)
    CASE 8
      PRINT "        KLINGONS REMAINING";Int(K9)
    CASE ELSE
      PRINT "???:" SYSID
  END SELECT 
END SUB

SUB SRS QX, QY
  LOCAL X, Y, I
  PRINT:PRINT:PRINT

  PRINT "  X:|";
  FOR I = 1 TO 8
    PRINT " "+FORMAT$(I+(QX-1)*8, "%02g")+"|";
  NEXT I
  PRINT
  PRINT "  +------------------------------------"
  PRINT "  |####################################"
  PRINT "Y |# +-1- -2- -3- -4- -5- -6- -7- -8- #"
  FOR Y = 1 TO 8
    PRINT FORMAT$(Y+(QY-1)*8, "%02g")+"|# "+FORMAT$(Y)+"";
    FOR X = 1 TO 8
      PRINT " "+DRAWOBJECT$(GALAXY(X+(QX-1)*8,Y+(QY-1)*8))+" .";
    NEXT X
    PRINT "#";
    PRINTSYSINFO Y
    'PRINT
  NEXT Y
  PRINT "  |####################################"

END SUB

IF STARBASES_TOTAL < 1 THEN
  X = RND1TO8()
  Y = RND1TO8()
  ' 1 = KLINGONS
  IF COUNTINQUADRANT(X, Y, 1) < 1 THEN 
    PUTOBJECTS X, Y, 1, 1
    KLINGONS_TOTAL = KLINGONS_TOTAL + 1
  ENDIF
  ' 2 = STARBASES
  PUTOBJECTS X, Y, 1, 2
  STARBASES_TOTAL = 1
ENDIF

' DETERMENING ENETRPRIZE POSITION
PUTX = 0: PUTY = 0
PUTOBJECT RND1TO8(), RND1TO8(), 9
ENTERPRISE(1) = PUTX
ENTERPRISE(2) = PUTY





PRINT
FOR I = 1 TO 64+9
  PRINT "-";
NEXT I
PRINT
FOR Y = 1 TO 64
PRINT "|";
FOR X = 1 TO 64
'PRINT "("X","Y")="GALAXY(X,Y)" ";
PRINT  DRAWOBJECT$(GALAXY(X,Y));
IF X MOD 8 = 0 THEN PRINT "|";
NEXT X
PRINT 
IF Y MOD 8 = 0 THEN 
  FOR I = 1 TO 64+9
    PRINT "-";
  NEXT I
  PRINT
ENDIF
NEXT Y

QUADRANTX = INT((ENTERPRISE(1)-1) \ 8) +1 
QUADRANTY = INT((ENTERPRISE(2)-1) \ 8) +1 


PRINT "KLINGONS: " KLINGONS_TOTAL
PRINT "STARBASES: " STARBASES_TOTAL
PRINT "STARS: " STARS_TOTAL
PRINT "ENTERPRIZE IS IN : (X="; ENTERPRISE(1); ", Y="; ENTERPRISE(2); ")"
PRINT "QUADRANT IS : (X="; QUADRANTX; ", Y="; QUADRANTY; ")"


SRS QUADRANTX, QUADRANTY



END
PRINT "0:" INT((0-1) \ 8) +1  
PRINT "64:" INT((64-1) \ 8) +1  
PRINT "8:" INT((8-1) \ 8) +1  
PRINT "9:" INT((9-1) \ 8) +1  