
' Get random integer number from 1 to 8
Function RND1TO8(R)
  RR = Int(Rnd(R)*7.98+1.01)
  'PRINT "RANDOM ="RR
  RND1TO8=RR 
End Function

SUB FINDEMPTY(QX, QY, OBJECT)

FOUND=0
DO WHILE FOUND=0
  X = RND1TO8(1)+((QX-1)*8)
  Y = RND1TO8(1)+((QY-1)*8)
  PRINT X,Y
  IF GALAXY(X,Y) = 0 THEN
    FOUND=1
    GALAXY(X,Y) = OBJECT
  ENDIF 
LOOP

PRINT "QUADRANT X ="QX", QUADRANT Y ="QY
PRINT X,Y
PRINT "("X","Y")="GALAXY(X,Y)



'PRINT "QUADRANT X="QX", QUADRANT Y="QY
'FOR Y = 1 TO 8
'  FOR X = 1 TO 8
'    PRINT "("X+(QX-1)*8","Y+(QY-1)*8")="GALAXY(X+(QX-1)*8,Y+(QY-1)*8);
'  NEXT X
'  PRINT
'NEXT Y   
'PRINT

END SUB

SUB PLACEOBJECT(QX, QY, COUNT, OBJECT)
END SUB

' GENERATING GALAXY
DIM GALAXY(64,64)
' GALAXY CODES:
' 1 - KLINGON
' 2 - STARBASE
' 3 - STAR



DIM QUADRNTS(8,8)

FOR QY = 1 TO 8
  FOR QX = 1 TO 8

    KLINGONS_IN_QUADRANT = 0
    R1=Rnd(1)
    If R1>.80 Then KLINGONS_IN_QUADRANT=1
    If R1>.95 Then KLINGONS_IN_QUADRANT=2
    If R1>.98 Then KLINGONS_IN_QUADRANT=3

    STARBASES_IN_QUADRANT = 0
    If Rnd(1)>.96 Then B3=1

    STARS_IN_QUADRANT = RND1TO8()


  NEXT QX
NEXT QY







PRINT
FOR Y = 1 TO 64
FOR X = 1 TO 64
'PRINT "("X","Y")="GALAXY(X,Y)" ";
PRINT GALAXY(X,Y);
IF X MOD 8 = 0 THEN PRINT " ";
NEXT X
PRINT 
IF Y MOD 8 = 0 THEN PRINT 
NEXT Y
